from .DatasusLinkScrapper import DatasusLinkScrapper , DatasusDataInfo
from .IbgePibCidadesScrapper import IbgePibCidadesScrapper , BaseFileType
from .IbgeMunicScrapper import IbgeBasesMunicScrapper
from .CityPaymentsScrapper import CityPaymentsScrapper
from .FormalJobsScrapper import FormalJobsScrapper
from .IdhScrapper import IdhScrapper
from .SnisScrapper import SnisScrapper
from .AnatelScrapper import AnatelFixedConnectionScrapper
from .IbgeCitiesNetworkScrapper import IbgeCitiesNetworkScrapper
from .HigherEducaPositionsScrapper import HigherEducaPositionsScrapper
