from .DatasusLinkScrapper import DatasusLinkScrapper , DatasusDataInfo
from .IbgePibCidadesScrapper import IbgePibCidadesScrapper , BaseFileType
from .IbgeMunicScrapper import IbgeBasesMunicScrapper
from .CityPaymentsScrapper import CityPaymentsScrapper
from .FormalJobsScrapper import FormalJobsScrapper