from .DatasusLinkScrapper import DatasusLinkScrapper , DatasusDataInfo
from .IbgePibCidadesScrapper import IbgePibCidadesScrapper , BaseFileType
from .IbgeMunicScrapper import IbgeMunicScrapper
from .CityPaymentsScrapper import CityPaymentsScrapper
from .FormalJobsScrapper import FormalJobsScrapper
from .IdhScrapper import IdhScrapper
from .AnatelScrapper import AnatelFixedConnectionScrapper
from .IbgeCitiesNetworkScrapper import IbgeCitiesNetworkScrapper
from .HigherEducaPositionsScrapper import HigherEducaPositionsScrapper
from .SchoolDistortionRatesScrapper import SchoolDistortionRatesScrapper
from .TechEquipamentScrapper import TechEquipamentScrapper
from .IdebFinalYearsScrapper import IdebFinalYearsScrapper
